### ISSUE TITLE
add_layout function query

### ISSUE THREAD

**Issue by aeroflux** [cjdoris/Bokeh.jl#28]
Hi Cj, thank you so much for writing this library, it has been a pleasure to use.

I have a query though. I have been wanting to add colorbars and multiple axes to a plot but can't seem to find a way to add a layout.

`
p.add_layout(..)
`

Couldn't find a reference of it in your source code. Am I missing something or is there the option to add this call?
Many thanks

**Comment by cjdoris** [comment]
The [`plot!` function](https://cjdoris.github.io/Bokeh.jl/stable/plotting/#Bokeh.plot!) is actually for adding any visible element to a plot, not just glyphs (scatters, lines, etc) but also axes, legends, titles, etc.

(Sorry for the slow response, this got lost in my inbox.)
